target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "SIM", "ARG", "C4", "FA", "PL", "RUF"]
ignore = ["E501", "B904", "PLR0913", "PLR2004", "ARG002"]

[format]
quote-style = "double"
indent-style = "space"
